/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.fuploadr;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int Button01=0x7f050005;
        public static final int Button02=0x7f050006;
        public static final int DescriptionText=0x7f050009;
        public static final int LinearLayout01=0x7f050000;
        public static final int LinearLayout02=0x7f050002;
        public static final int LinearLayout03=0x7f050003;
        public static final int ScrollView01=0x7f050007;
        public static final int TagsText=0x7f05000b;
        public static final int TextView01=0x7f050001;
        public static final int TextView02=0x7f050004;
        public static final int TextView03=0x7f05000a;
        public static final int TitleText=0x7f050008;
    }
    public static final class layout {
        public static final int authentication=0x7f030000;
        public static final int upload_photo=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int authenticate_done=0x7f040005;
        public static final int settings_account_authorize=0x7f040007;
        public static final int settings_account_new=0x7f040008;
        public static final int settings_defaults=0x7f040006;
        public static final int upload_description=0x7f040002;
        public static final int upload_tags=0x7f040003;
        public static final int upload_title=0x7f040001;
        public static final int upload_upload=0x7f040004;
    }
}
